<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>MultiShop.Order.WebApi</UserSecretsId>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\MultiShop.Order.Application\MultiShop.Order.Application.csproj" />
      <ProjectReference Include="..\..\Infrastructure\MultiShop.Order.Persistence\MultiShop.Order.Persistence.csproj" />
      <ProjectReference Include="..\..\..\Message\MultiShop.MessageBus\MultiShop.MessageBus.csproj" />
    </ItemGroup>

</Project>
