<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>MultiShop.WebUI</UserSecretsId>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\help-documentation\assets\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\help-documentation\assets\blueprint-css\plugins\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\app\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\charts\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\component\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\dist\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\forms\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\maps\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\pages\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\tables\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\online-shop-website-template-original-backup\.DS_Store" />
      <Content Include="wwwroot\online-shop-website-template-original-backup\lib\.DS_Store" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\Data\" />
      <Folder Include="Areas\Admin\Models\" />
      <Folder Include="Areas\Admin\Pages\" />
      <Folder Include="Areas\User\Data\" />
      <Folder Include="Areas\User\Models\" />
      <Folder Include="Areas\User\Pages\" />
      <Folder Include="Areas\User\Views\" />
      <Folder Include="Pages\Shared\Components\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.3" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\Admin\Views\Category\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\Comment\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\Comment\Update.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\FeatureSlider\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\OfferDiscount\Create.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\OfferDiscount\Index.cshtml" />
      <AdditionalFiles Include="Areas\Admin\Views\OfferDiscount\Update.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MultiShop.Dtos\MultiShop.Dtos.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Auth\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Auth\Register.cshtml" />
    </ItemGroup>

</Project>
