<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\help-documentation\assets\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\help-documentation\assets\blueprint-css\plugins\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\app\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\charts\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\component\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\dist\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\forms\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\maps\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\pages\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\MainDownload-OvioAdmin-html5-template\html\tables\et-line-font\fonts\.DS_Store" />
      <Content Include="wwwroot\online-shop-website-template-original-backup\.DS_Store" />
      <Content Include="wwwroot\online-shop-website-template-original-backup\lib\.DS_Store" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\Data\" />
      <Folder Include="Areas\Admin\Models\" />
      <Folder Include="Areas\Admin\Pages\" />
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\Admin\Views\Category\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MultiShop.Dtos\MultiShop.Dtos.csproj" />
    </ItemGroup>

</Project>
